/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarEventsRouteImport } from './../routes/_sidebar/events'
import { Route as SidebarEventsEventIdRouteImport } from './../routes/_sidebar/events.$eventId'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarEventsRoute = SidebarEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarEventsEventIdRoute = SidebarEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => SidebarEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof SidebarEventsRouteWithChildren
  '/profile': typeof SidebarProfileRoute
  '/events/$eventId': typeof SidebarEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof SidebarEventsRouteWithChildren
  '/profile': typeof SidebarProfileRoute
  '/events/$eventId': typeof SidebarEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/events': typeof SidebarEventsRouteWithChildren
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/events/$eventId': typeof SidebarEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events' | '/profile' | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events' | '/profile' | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/events'
    | '/_sidebar/profile'
    | '/_sidebar/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/events': {
      id: '/_sidebar/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof SidebarEventsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/events/$eventId': {
      id: '/_sidebar/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof SidebarEventsEventIdRouteImport
      parentRoute: typeof SidebarEventsRoute
    }
  }
}

interface SidebarEventsRouteChildren {
  SidebarEventsEventIdRoute: typeof SidebarEventsEventIdRoute
}

const SidebarEventsRouteChildren: SidebarEventsRouteChildren = {
  SidebarEventsEventIdRoute: SidebarEventsEventIdRoute,
}

const SidebarEventsRouteWithChildren = SidebarEventsRoute._addFileChildren(
  SidebarEventsRouteChildren,
)

interface SidebarRouteRouteChildren {
  SidebarEventsRoute: typeof SidebarEventsRouteWithChildren
  SidebarProfileRoute: typeof SidebarProfileRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarEventsRoute: SidebarEventsRouteWithChildren,
  SidebarProfileRoute: SidebarProfileRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
